### PR TITLE
Basic minc tracklists support (MASS ISRC list paste)

### PR DESCRIPTION
**Pull request by jesus2099**
This is the draft of a PR for “Support pasting multiple isrcs.” (kepstin/magicisrc#1)

It allows to paste a bunch of ISRC starting from whichever track input field.
- It works with minc tracklists.
- It does not skip tracks with no ISRC.
  It may be difficult to do in the future with my current approach.
- @kepstin, sendEvent is ATM useless, I can remove it.

### CODE REVIEW

**Comment by jesus2099** [comment]
Tell me what to change in my code to suit your tastes or anything. :)

**Comment by kepstin** [comment]
Hmm. I think rather than allowing people to paste multiple ISRCs into the existing text boxes, it would be better to have a (large?) text field, probably at the top, to paste blocks of text. I'd want to do explicit parsing - i.e. have a "Parse" button beside it rather than automatically parse on paste, and maybe a select box to choose the disk to apply the isrcs to ("all disks", "disk 1", "disk 2", etc)

Please don't put a version number in the title.

**Comment by jesus2099** [comment]
The ability to **paste in any track** was useful to me for releases with holes like the following, where I had to use notlob.eu because of skip tracks (`isrcsubmit.exe` cannot cope when there are holes, at least especially when there is no ISRC on track 1):
- https://musicbrainz.org/edit/13349880
- https://musicbrainz.org/edit/14065037
- https://musicbrainz.org/edit/17991105
- https://musicbrainz.org/edit/18227856
- https://musicbrainz.org/edit/18503334
- https://musicbrainz.org/edit/19274139

Even in minc, it’s not really rare (they reflect what’s on CD BTW).
Let’s take [Edit #18227856 - Add ISRCs](https://musicbrainz.org/edit/18227856) to illustrate what I mean:
1. I used `mediatools.exe` — same with [minc’s SRCL-2471 page](https://www.minc.gr.jp/db/AlbInfo.aspx?CAT1=SRCL&CAT2=2471) — to display the ISRC table
2. I can copy rows 2 and 3
3. Paste them in your page’s 2nd track
4. Copy remaining rows 9〜14
5. Paste them in your page’s 9th track

This way I can submit 8 ISRC with only two copy/pastes instead.

I tried it with the data (both `mediatools.exe` and minc verbatims) you can copy from the edit note I’ve linked and the release MBID that’s over there as well.

---

The ability to **not stop at a medium’s end** is that I can use the above method to cover any amount of mediums.

---

Covering those cases would be made more complex with one or several separate text areas and some select combos. No ?

**Comment by jesus2099** [comment]
# “track skip” demo

mass magicisrc with track skip

**Comment by jesus2099** [comment]
# “medium span” demo

mass magicisrc with medium span

**Comment by jesus2099** [comment]
I close this as it was for previous version of MAGIC ISRC. :)

**Pull request closed without merging**
